### ISSUE TITLE
Troubleshooting Converting Figma to HTML

### ISSUE THREAD

**Issue by aaronsun1030** [karthikRavichandran/students-event-tracking-system#2]
@DeepaRukminiMahalingappa Here is a screenshot of exactly what I did to export the Figma page to HTML. On the left is the anima plugin, which I access in developer mode (the green </> selection signifies developer mode). Then, I select **the entire layer as a page** so that on the left tab, all of the components of the layer (here it's `#grade-analytics, logo menu`, etc) and the preview on the plugin matches what I want to export. Then I hit export and get an output. I'm not sure what happened with your export, but I noticed the export path was `/Student Event Tracking Dashboard/Dashboard/index.html`, but mine is a totally random path `AnimaPackage-Html-PWyVR/index.html`.
![image](https://github.com/karthikRavichandran/students-event-tracking-system/assets/57044175/7143050b-6a9e-40cb-a2ef-fb9fd3be18b3)
Tell me if this makes sense.

**Comment by DeepaRukminiMahalingappa** [comment]
<img width="1440" alt="Screenshot 2023-12-03 at 11 46 20 AM" src="https://github.com/karthikRavichandran/students-event-tracking-system/assets/115872430/cabe8d7b-03fb-4896-8b0a-c077ecc634ff">

<img width="1440" alt="Screenshot 2023-12-03 at 11 46 33 AM" src="https://github.com/karthikRavichandran/students-event-tracking-system/assets/115872430/06e13139-7edf-413b-ac2f-dc3284eb4d37">


I converted Figma to HTML using Anima Plugin as per you suggested. To download code it is asking to unlock pro-features. Can you share the source code what you have downloaded, so that I can check the the root folder.

**Comment by aaronsun1030** [comment]
Check out the feature/html branch, I pushed the files.

**Comment by karthikRavichandran** [comment]
No longer this issue is valid-- we moved away from Figma-HTML conversion tasks
